# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5a6376718f71e0d903ce3e8a78bae25c405df65e017810bf3f8e2cc2e65ac97de3a434997374a24f20ce07d1d6c502627d959f276c55175fb614a8e7e691d03

test:
  secret_key_base: ef50bfcd0aaafcfad064eed8214fd8d5b77bad3b1c58da0ccc80bcb293b63cc3e2f46ea5fe51d45c5d601d94da382af315dce086aeacdae980405739bc0a707f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
